# docker-compose.yml
version: "3.6"
services:
  existdb:
    image: stadlerpeter/existdb:latest
    environment:
      - EXIST_PASSWORD_FILE=/run/secrets/existdb_passwd
    restart: unless-stopped
    ports:
      - 8080:8080
    secrets:
      - source: existdb_passwd
    volumes:
      - ./existdb/existdb_data:/opt/exist/data
secrets:
  existdb_passwd:
    file: ./existdb/password-file
