# docker-compose.yml
version: "3.6"
services:
  nginx:
    image: nginx
    ports:
      - 8081:8081
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "webpack"
  webpack:
    image: node:14.16-alpine3.13
    volumes:
      - ./:/usr/app/
    working_dir: /usr/app/
    command: "npm run serve -- --port 8081"
  existdb:
    image: stadlerpeter/existdb:latest
    environment:
      - EXIST_PASSWORD_FILE=/run/secrets/existdb_passwd
    restart: unless-stopped
    ports:
      - 8080:8080
    secrets:
      - source: existdb_passwd
    volumes:
      - ./existdb/existdb_data:/opt/exist/data
secrets:
  existdb_passwd:
    file: ./existdb/password-file
