# docker-compose.yml
version: "3.6"
services:
  existdb:
    image: stadlerpeter/existdb:5.4
    restart: unless-stopped
    environment:
      - EXIST_PASSWORD_FILE=/run/secrets/existdb_passwd
      - EXIST_ENV=development
      - EXIST_CONTEXT=/exist
    volumes:
      - ./existdb/existdb_data:/opt/exist/data
      - ./existdb/existdb_logs:/opt/exist/logs
    ports:
      - 8080:8080
    secrets:
      - source: existdb_passwd
secrets:
  existdb_passwd:
    file: ./existdb/password-file
